---
title: "Workshop Overview:"
subtitle: "For A Data Pre-Analysis Plan Using Canva"
excerpt: "Join us for a 30-minute hands-on workshop where we will explore the world of effective data pre-analysis planning using Canva. We'll use a real dataset to address common challenges, such as having a narrow perspective on your data. Together, we'll work to improve your data analysis decision-making skills.


Have you ever wished for a visual aid to communicate your analysis plan? You're in luck! No previous knowledge of Canva is required – just bring your curiosity and enthusiasm!"
date: "2024-03-18"
author: "Laura Briggs"
draft: false
layout: single
images:
categories:
- "Data analysis"
- "GSD data"
- "R tutorial"
- "Workshop"
- "Presentation"
tags:
- "post_id: 004"
- "Data cleaning"
- "GSD health data"
---

### A Data Pre-Analysis Plan Using Canva: Workshop Description

This 30-minute hands-on workshop will introduce you to the world of effective data pre-analysis planning using Canva. Delivered through a completed example with a real dataset, you'll gain insights into overcoming challenges such as a myopic view of your data and improving your data analysis decision-making skills. Wish you had a visual aid to communicate your analysis plan? Then join me for a practical session that transforms how you approach data analysis! No previous knowledge of Canva is required.

### Intended Audience

This workshop is designed for anyone who has a keen interest in data analysis. No previous knowledge of the tool, Canva, is required. However, it will be helpful if you have an understanding of a few fundamental terms used in R Studio such as categorical variable and dataframe. Questions are encouraged during the workshop!

- Faculty Members
- Graduate Students
- Undergraduate Students
- UVic Staff
- General Public

### Learning Outcomes

By the end of this workshop, participants will be able to:

- Understand the advantages of creating a data pre-analysis plan in Canva. 
- Identify the six sections of a robust data pre-analysis plan. 
- Know how to add and read comments on an existing data pre-analysis plan in Canva.
- Recognize when and how to integrate a data pre-analysis plan into their own projects.
- Leave with an editable version of the example discussed in the workshop that can be modified to suit their own work. 

### Agenda

The agenda for today's workshop is outlined below.

1. Introduction & Demonstration of the Data Pre-Analysis Plan in Canva (7 min)
2. Explanation of the Activity (3 min)
3. The Activity (10 min)
4. Group Discussion (5 min)
5. Additional Resources (2 min)
